version: '3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cykel
      - POSTGRES_PASSWORD=password
  cykel:
    build: cykel
    ports:
      - "8000:8000"
    volumes:
      - media:/cykel/media
    environment:
      - SECRET_KEY=fooooo
      - ALLOWED_HOSTS=0.0.0.0,localhost
      - DATABASE_URL=postgis://postgres:password@db:5432/cykel
      - UI_SITE_URL=http://localhost
      - CORS_ORIGIN_WHITELIST=http://localhost
    depends_on:
      - db
  voorwiel:
    build: voorwiel
    # environment:
    #   - NODE_ENV=config_name

volumes:
  data:
  media:
